# https://taskfile.dev
version: '2'
tasks:

  run:
    desc: start the development server and visit
    cmds:
      - open http://localhost:8000/admin
      # 0 is a shortcut for 0.0.0.0
      - pipenv run python manage.py runserver 0:8000
  sh:
    cmds:
      - pipenv run ./manage.py shell
  psh:
    cmds:
      - pipenv shell

  mig:
    cmds:
      - pipenv run python manage.py migrate

  # polls app migration operations:
  # python manage.py makemigrations polls
  # python manage.py sqlmigrate polls 0001

  sql:
    cmds:
      - mycli -uroot django_getting_started
      # or pipenv run ./manage.py dbshell

  # admin
  create-admin-user:
    cmds:
      # admin/admin admin@demo.local
      - pipenv run python manage.py createsuperuser

  db-create:
    cmds:
      - mysql -uroot -p -e "create database if not exists django_getting_started;"

  install:
    cmds:
      - pipenv install

  init-polls:
    cmds:
      - python manage.py startapp polls
      
  init-mysite:
    cmds:
      - pipenv run django-admin startproject mysite .

  init-install:
    desc: install Django and verify version
    cmds:
    - pipenv install Django
    - pipenv run python -c "import django; print(django.get_version())"
    # Django 3.1, which supports Python 3.6 and later
    - pipenv run python -m django --version
